# Android signing properties
# Replace the values below with your real credentials
PK_KEYSTORE_PATH=../app-signing/apk-signing.jks
PK_KEYSTORE_PASSWORD=your_keystore_password
PK_KEY_ALIAS=pk_upload
PK_KEY_PASSWORD=your_key_password
